language:
    - r
    - cpp

cache: packages
sudo: required

compiler:
    - clang
    - gcc
    - g++

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh install_aptget r-cran-rmpi
addons:
  apt:
    packages:
      - libudunits2-dev  


env:
  global:
    - CRAN: http://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change
